baseURL = "https://coolbeevip.github.io/"
languageCode = "en-us"
theme = "anatole"
enableEmoji = true

[params]
title = "I'm Lei Zhang"
author = "Lei Zhang"
description = "This is my knowledge base. I document things here"
profilePicture = "images/profile.jpg"
favicon = "favicons/"
#displayMode = "dark"
disableThemeSwitcher = true
readMore = true
fullPostContent = false
customCss = ["css/custom.css"]
mainSections = []
googleAnalytics = "G-0JGN8RJDND"

[params.math]
enable = true
use = "katex"

## Social links

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/coolbeevip/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:zhanglei@apache.org"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  identifier = "blog"
  weight = 200
  url = "/posts"

  [[menu.main]]
  name = "Bookmarks"
  identifier = "bookmarks"
  weight = 300
  url = "/bookmarks"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "3.about"
  url = "/about/"
